### ISSUE TITLE
Havok triggers entity removal in a limited world incorrectly

### ISSUE THREAD

**Issue by Phoenix84** [KeenSoftwareHouse/SpaceEngineers#158]
With a limited world size, if I change the position in ModAPI scripting on an entity to near the border (but still 10+km away from border), then havok triggers the HavokWorld_EntityLeftWorld event and deletes the entity.

This causes the entity to disappear, and the player left floating, however there's no HUD warning that you are near the border. You can still move away from the center much further before reaching the real end.

I'm attaching the world and my mod, which trigger it.
To reproduce, simply load the world with the mod, enter the cockpit, and press 1.

**Comment by joemorin73** [comment]
With today's potential addition of Jump Drives.  Has this issue been corrected in the latest merge?

**Comment by Phoenix84** [comment]
Yes, this is still reproducible, and with the built-in version now as well.
See https://youtu.be/zjqtxBA7EdE

**Comment by joemorin73** [comment]
To understand,

Because the grid does not travel to it's destination, but rather appears at it's destination, the system can't split a cluster as the distance is too far?

Would this mean you could jump 100km if cluster was present at the destination?  (IE, someone was in the area.)

I haven't looked into the code, but I imagine the fix would require to create a new cluster if there is no cluster in the area or the cluster is too far?  This does present problems as cluster splitting is one thing, but creating a cluster and verifying anything in the area is added to the new cluster.

**Comment by Phoenix84** [comment]
That's how I understand it.
Creating a new cluster is probably the correct fix, or add to an existing overlapping cluster, then possibly split that.

**Comment by joemorin73** [comment]
Here's hoping it gets in for next Thursday.

**Comment by Phoenix84** [comment]
This is still a bug in 01_092_007, contrary to release notes.

**Comment by joemorin73** [comment]
We need a Github merge to see what they did to address it.

**Comment by zrisher** [comment]
I was really excited about this being fixed. : (

**Comment by devu** [comment]
Under what conditions is not working for you?
I tested it on 300km limit world and was able to jump to GPS over 100km
just fine.

**Comment by Phoenix84** [comment]
The world provided in the OP shows the problem.

**Comment by joemorin73** [comment]
Pheonix, you're testing this with your FTL mod as opposed to the Jump Drive.  Is your mod still the original code?  or is it now overriding the new JumpDrive.

I ask this because I am wondering if the fix is in the JumpDriveSystem and not in the MyCluster.

**Comment by Phoenix84** [comment]
Ugh, it does appear they fixed in the jump drive system. I can't reproduce it with the vanilla jump drive now.
That's not going to work. Any mod that changes the entity position is still affected by this.

Related to this, I found simply disabling the havok entity removed event handler isn't good enough. Starting about a week ago, on an unlimited world now (which doesn't use this event), the physics is detached, but the visual of the grid remains. This means when you exit the cockpit, you can pass through the ship and can't interact with any terminals. Now using an unlimited world is no longer a workaround.

**Comment by joemorin73** [comment]
I think there is a summer slowdown.  (Vacations and etc.)  We may be waiting until next week.

**Comment by joemorin73** [comment]
Github updated.  Time to see the fix.

**Comment by Phoenix84** [comment]
It's in Sources/Sandbox.Game/Game/GameSystems/MyGridJumpDriveSystem.cs line 624.
See the commit I referenced for the code. Unfortunately I don't think I can do that in my mod.

**Comment by joemorin73** [comment]
SO they address the issue in the jumpdrive instead of in the world movement?

**Comment by Phoenix84** [comment]
Yes, which is exactly what I suspected after the last update.

**Comment by zrisher** [comment]
Ever since the 7/24 patch that "fixed" jump drive in its class instead of in the entity cluster logic, we've had issues (on our limited-size world) where ships will randomly disappear with no seeming common setup. They can be ships, stations, moving, not moving, piloted, completely empty, being welded, completely untouched, etc. I have a hunch that the common issue is in fact that someone **else** is using jump drive at the time, because:
* the disappearance (immediately, no messages, kicks you out of cockpit) is so similar to what we saw with broken jump drive
* no one seems to be experiencing this except on high populated limited-size worlds
* everyone who's experienced this recently has confirmed they believed someone else was using jump drive at the time (but obviously this is hard to correlate on a survival PVP server)

@Phoenix84 do you think this might make sense given the existing issues with MyClusterTree? I haven't had a chance to look into the code in depth here because there are some new concepts I'm unfamiliar with, but I will get to it soon. Just curious what your thoughts are.

In the mean time, I've disabled the jump drive block in the hopes that will help.

**Comment by Phoenix84** [comment]
@zrisher With the way the cluster code works, it can affect any and all objects, even ones not performing the jump.
I'm not sure if the fix itself runs on the client, server, or both. If it only runs on on side that triggered the jump, that might explain the disappearance, as the other clients won't get the hint to be careful with the next cluster operation.
Plus, I think this fix is really a test or workaround. Which is why the put it in the jump code instead of the cluster code. If it works, they move it to the cluster code, if not, they figure something else out.
It reduces the likelihood for regression, so I understand.
Sounds like it's not working though. 
As for disabling the jump drive, that should work to fix it, as long as you don't have a high speed limit mod (like several km/s at least). The jump drive issue doesn't cause the problem, it's a symptom.

**Comment by zrisher** [comment]
That's exactly what I wanted to hear. Thank you so much for the insight!

**Comment by midspace** [comment]
zrisher said:
> Ever since the 7/24 patch that "fixed" jump drive in its class instead of in the entity cluster logic, we've had issues (on our limited-size world) where ships will randomly disappear with no seeming common setup.

Not necessarily. There was an issue I saw a few months ago before Jump drives came long, where a ship would mysteriously move somewhere else.
I had it happen on a dedicated test server that I have no admin access to, and I was by myself at the time. It was small ship, with power and dampeners turned on so it didn't drift away if knocked, and ownership set to me. One moment it was there when I went past, perhaps 20 minutes later I noticed it was missing. It certainly wasn't knocked, or hit by anything. No debis. I had to save the game locally to use SEToolbox to find it had moved 100Km away. After flying there in another ship, the ship was still intact and motionless, and still under the correct ownership. There was no explanation as to why it suddenly moved 100Km away.

**Comment by zrisher** [comment]
In our case, the ships are all actually disappearing. We have a mod that allows players to see the positions of all their owned grids - the ships we've seen disappear are completely and instantly removed from the game.

FYI I disabled jump drives via `Enabled="False"` on the block definition last night, and I haven't had a single report of the above error since. I was getting about 5 a day before that. So I do believe this is related.

**Comment by Phoenix84** [comment]
Since this is a problem in the cluster code, what midspace is saying is it's possible you will still see this bug randomly.
However with the jump drive disabled, the conditions to trigger that problem are much less likely to occur.
I agree, you might still hit this randomly, but maybe 1 in 10000, as opposed to 1 in 10.

**Comment by zrisher** [comment]
Sorry I forgot to update this thread - it turned out that even with jump drives off, the disappearance would regularly occur. So basically there is no way to run a Limited-Size world without ships randomly disappearing.

**Comment by jpcsupplies** [comment]
I can concur on this - I always run my servers on unlimited, as we regularly manually clean up debris on our server; and any missing ship always turn up elsewhere; i've not had a ship simply vanish on me.
Exploration mode structures on the other hand..  i've seen these spawn/despawn with no obvious pattern, other than being located where no player has been recently.
My own players report ships on other limited servers simply vanishing; one server got so bad all the players moved to mine which is where i found out about it.

**Comment by Phoenix84** [comment]
This was fixed in the stock jump drive some time ago by calling Sandbox.Engine.Physics.MyPhysics.Clusters.EnsureClusterSpace().
Is there any chance, @OndrejPetrzilka, that you will be able to make this available to modders? Right now mods still cannot teleport entities very far without hitting the cluster limitation and disappearing.
